language: node_js
node_js:
  - stable
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_script:
  - npm install -g aglio
script:
  - bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "91dc7b3864c4"
  - COMMIT_AUTHOR_EMAIL: "shaarli@hoa.ro"

  